### ISSUE TITLE
Implement Data Extraction Operation for Additional Fields - Weekly Depth Charts

### ISSUE THREAD

**Issue by dataengineergaurav** [ggurjar333/NFL-Stats#13]
**Description:**
As part of our ongoing efforts to enhance the functionality of the AdditionalFields service, there's a need to implement a data extract operation for improving the handling of Weekly Depth Charts.

Provides depth chart information for each team for a given week.

**Tasks:**

- [x] Implement a new function for extracting the data.
- [x]  Write appropriate unit tests for the new functionality to ensure reliability and ease of integration.

**Acceptance Criteria:**

- [x]  The raw data from the AdditionalFields service should be successfully extracted.
- [x]  The extraction function should complete unit test coverage and pass its test.
- [x]  Ensure that the changes do not break any existing functionality of the AdditionalFields service.
