### ISSUE TITLE
Implement Data Transform Operation for current season schedule, current week schedule, season schedule of PrimaryFeeds

### ISSUE THREAD

**Issue by dataengineergaurav** [ggurjar333/NFL-Stats#36]
As part of our ongoing efforts to enhance the functionality of the PrimaryFeeds service, there's a need to implement a data transform operation for improving the handling of current season schedule, current week schedule, season schedule.

**Tasks:**
- [x] Implement a new function for transform the raw current season schedule data into a structured format that's easy to process.
- [x]  Implement a similar function for the current week schedule data.
- [x]  Develop a function for dealing with the season schedule data.
- [x]  Write appropriate unit tests for the new functionality to ensure reliability and ease of integration.

**Acceptance Criteria:**
- [x]  The raw data from the PrimaryFeeds service should be successfully transformed.
- [x]  The transformation functions should have complete unit test coverage and should pass all tests.
- [x]  Ensure that the changes do not break any existing functionality of the PrimaryFeeds service.

**Comment by jbassie** [comment]
Please change label ffrom gamefeeds to PlayerFeeds

**Comment by dataengineergaurav** [comment]
> Please change label ffrom gamefeeds to PlayerFeeds

Good catch! 👍
