### ISSUE TITLE
Implement Data Transform Operation for Player profile from Player Feeds

### ISSUE THREAD

**Issue by dataengineergaurav** [ggurjar333/NFL-Stats#37]
As part of our ongoing efforts to enhance the functionality of the PlayerFeeds service, there's a need to implement a data transformation operation for improving the handling of player profile.

Provides player biographical information, draft information, and seasonal statistics for the regular season and postseason.

**Tasks:**
- [x] Implement a new function for transforming the data.
- [x] Write appropriate unit tests for the new functionality to ensure reliability and ease of integration.

**Acceptance Criteria:**

- [x] The raw data from the PlayerFeeds service should be successfully transformed.
- [x] The transformation function should complete unit test coverage and pass its test.
- [x] Ensure that the changes do not break any existing functionality of the PlayerFeeds service.
